# Generated by Django 5.1.3 on 2025-03-04 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
