# Generated by Django 5.1.3 on 2025-03-05 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_remove_student_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentFeedBack',
        ),
    ]
