# Generated by Django 5.1.3 on 2025-03-05 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0004_delete_studentfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Course Content Quality', 'Course Content Quality'), ('Instructor Performance', 'Instructor Performance'), ('Platform Usability', 'Platform Usability'), ('Live Session Experience', 'Live Session Experience'), ('Assignment/Task Relevance', 'Assignment/Task Relevance'), ('Certification Process', 'Certification Process'), ('Support/Customer Service', 'Support/Customer Service'), ('Payment Issues', 'Payment Issues'), ('Other', 'Other')], max_length=50)),
                ('custom_category', models.CharField(blank=True, max_length=255, null=True)),
                ('feedback_text', models.TextField()),
                ('rating', models.IntegerField()),
                ('suggestions', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='feedback_uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_system_feedback', to='Students.student')),
            ],
        ),
    ]
