# Generated by Django 5.1.3 on 2025-03-05 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0005_studentfeedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentfeedback',
            old_name='teacher',
            new_name='student',
        ),
    ]
