# Generated by Django 5.1.3 on 2025-03-05 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0006_rename_teacher_studentfeedback_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentFeedback',
        ),
    ]
