# Generated by Django 5.1.3 on 2025-03-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0010_alter_payment_order_id_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(help_text='rupees'),
        ),
    ]
