# Generated by Django 5.1.3 on 2025-03-15 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0013_usercalendarevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('count', models.PositiveIntegerField(default=1)),
                ('last_searched', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-count'],
            },
        ),
    ]
