# Generated by Django 5.1.3 on 2025-03-06 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0013_usercalendarevent'),
        ('Teachers', '0002_alter_receivedpayment_duration'),
        ('videoconference_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinars_teacher', to='Teachers.teacher'),
        ),
        migrations.CreateModel(
            name='WebinarAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('join_time', models.DateTimeField(blank=True, null=True)),
                ('leave_time', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinars_std_att', to='Students.student')),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinars_std_id', to='videoconference_app.webinar')),
            ],
            options={
                'unique_together': {('student', 'webinar')},
            },
        ),
    ]
