# Generated by Django 5.1.3 on 2025-03-04 10:52

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdsPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/')),
                ('link', models.URLField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('link', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementSmall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('link', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_head', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('desc', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('course_img', models.ImageField(blank=True, null=True, upload_to='content_images/')),
                ('course_video', models.FileField(blank=True, null=True, upload_to='content_videos/')),
                ('order', models.PositiveIntegerField(help_text='Order in the course module')),
                ('is_mandatory', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('description2', models.TextField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(help_text='Duration in hours')),
                ('course_img', models.ImageField(blank=True, default='default_images/default.png', null=True, upload_to='course_images/')),
                ('category', models.CharField(choices=[('Programming Language', 'Programming Language'), ('Data Science', 'Data Science'), ('Web Development', 'Web Development'), ('Game Development', 'Game Development'), ('Mobile Development', 'Mobile Development'), ('Database Design', 'Database Design'), ('Software Testing', 'Software Testing'), ('Software Engineering', 'Software Engineering'), ('Software Development Tools', 'Software Development Tools'), ('No-Code Development', 'No-Code Development'), ('Other', 'Other')], max_length=100)),
                ('old_price', models.PositiveIntegerField(default=0, help_text='old price')),
                ('price', models.PositiveIntegerField(default=0, help_text='new price')),
                ('rating', models.PositiveIntegerField(blank=True, help_text='rating 1 to 5', null=True)),
                ('enroll', models.PositiveIntegerField(blank=True, help_text='no of student that have enroll', null=True)),
                ('max_enrollments', models.PositiveIntegerField(blank=True, help_text='total no of student that can enroll', null=True)),
                ('like', models.PositiveIntegerField(default=0, help_text='no. of likes')),
                ('dislike', models.PositiveIntegerField(default=0, help_text='no. of dislikes')),
                ('is_display', models.BooleanField(default=False)),
                ('is_content', models.BooleanField(default=False)),
                ('is_data', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting_code', models.CharField(blank=True, max_length=10, null=True)),
                ('months', models.PositiveIntegerField(default=3, help_text='no. of months its take to complete course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, default='default_images/default.png', null=True, upload_to='course_comments/')),
                ('comment', models.TextField()),
                ('value', models.BooleanField(default=False, help_text='Indicates whether the content is liked by the user')),
            ],
        ),
        migrations.CreateModel(
            name='CourseFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseLearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learn', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EdUContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whoCan', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EduFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='edufeed/')),
                ('description', models.TextField(blank=True, help_text='background', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EduForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='background', null=True)),
                ('mail_id', models.EmailField(max_length=254)),
                ('m_no', models.PositiveIntegerField(help_text='mobile number')),
            ],
        ),
        migrations.CreateModel(
            name='EduOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='This is the email', max_length=254)),
                ('otp', models.PositiveIntegerField(help_text='OTP')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EduSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mail_id', models.EmailField(max_length=254)),
                ('from_pg', models.CharField(max_length=200)),
                ('num', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('assignment_submitted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='assignment_submissions/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('rework', 'Rework')], default='pending', max_length=10)),
                ('message', models.TextField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_submission', to='Course_Module.assignment')),
            ],
        ),
    ]
