# Generated by Django 5.1.3 on 2025-03-09 12:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_Module', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogress',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
