# Generated by Django 5.1.3 on 2025-03-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_Module', '0003_studentprogress_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.PositiveIntegerField(default=24, help_text='Duration in hours'),
        ),
        migrations.AlterField(
            model_name='course',
            name='enroll',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='no of student that have enroll', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='max_enrollments',
            field=models.PositiveIntegerField(blank=True, default=100, help_text='total no of student that can enroll', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='rating 1 to 5', null=True),
        ),
    ]
