# Generated by Django 5.1.3 on 2025-03-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedpayment',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in months', null=True),
        ),
    ]
