# Generated by Django 5.1.3 on 2025-03-04 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Course_Module', '0001_initial'),
        ('EduAssessment', '0001_initial'),
        ('Students', '0001_initial'),
        ('Teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='Students.student'),
        ),
        migrations.AddField(
            model_name='coursetime',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduAssessment.enrollment'),
        ),
        migrations.AddField(
            model_name='form',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms_course', to='Course_Module.course'),
        ),
        migrations.AddField(
            model_name='formaccesscontrol',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduAssessment.form'),
        ),
        migrations.AddField(
            model_name='formaccesscontrol',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.student'),
        ),
        migrations.AddField(
            model_name='message',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course_Module.course'),
        ),
        migrations.AddField(
            model_name='message',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.student'),
        ),
        migrations.AddField(
            model_name='message',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teachers.teacher'),
        ),
        migrations.AddField(
            model_name='question',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='EduAssessment.form'),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='EduAssessment.form'),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='EduAssessment.question'),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.student'),
        ),
    ]
